### ISSUE TITLE
Add puzzles mode

### ISSUE THREAD

**Issue by adityatendulkar** [CarbonChess/CarbonChess#9]
Another button would be added which adds a puzzle mode where the objective would be to find the best moves in a position. These puzzles would be sourced from [lichess' database](https://database.lichess.org/).

**Comment by Nixinova** [comment]
ReadCSV function:
```js
async function readCsv() {
	const CSV_URL = '...';
	const response = await fetch(CSV_URL);
	const rawData = response.text();
	const data = rawData.split('\n').map(arr => arr.split(/(?<!\\),/));
	for (let i in data) {
		for (let j in data[i]) {
		}
	}
}
```
